import { ValidatedFinding, ScanSummary } from './finding.types';

export type ScanStatus = 'pending' | 'scanning' | 'validating' | 'complete' | 'failed';

export interface ScanRequest {
  scanId?: string;      // Pre-generated by the controller; orchestrator reuses it when provided
  projectPath: string;
  projectName?: string;
  userId?: string;
}

export interface AgentStatus {
  agentId: string;
  agentName: string;
  status: 'waiting' | 'running' | 'complete' | 'error';
  filesAnalyzed: number;
  findingsCount: number;
  durationMs: number;
  error?: string;
}

export interface ScanResult {
  scanId: string;
  projectPath: string;
  projectName: string;
  score: number;
  status: ScanStatus;
  findings: ValidatedFinding[];
  agentStatuses: AgentStatus[];
  summary: ScanSummary;
  startedAt: string;
  completedAt?: string;
  durationMs?: number;
  armorIqPlanId?: string;
}
